Refactor server code
osherdp/porfavor pull request #10
Opened 2018-07-26 09:40 UTC by osherdp

2018-07-27 12:38 UTC, IamShobe approved these changes
Seems good 👍 
So now gunicorn is hosting the server?
Two questions: 
why is the server running with debug mode?
and how does the port changes if u expose port  8000 staticly?

2018-08-11 23:21 UTC, IamShobe requested changes
LOL Until now i didnt know i  needed to click  on finish review XDD

2018-08-11 23:21 UTC, IamShobe commented on src/porfavor/client.py
> +        str: bytes of the zip file containing required files.
str.

2018-08-11 23:21 UTC, IamShobe commented on src/porfavor/client.py
> +    filename = "{}.zip".format(project)
i dont know how to select multiple lines but i think that all of the below should be splited into a separate function.

2018-08-11 23:21 UTC, IamShobe commented on src/porfavor/client.py
>      publish(host=host,
i dont really see a reason for this split - its a function that calls another function and thats it.
better be splittingg the ffunction itself to logic parts and have an high abstraction level to read.

2018-08-11 23:21 UTC, IamShobe commented on src/porfavor/server/api.py
> +        return "No file was supplied in the request", 400
change return code to be used from httplib. this way is more readable

2018-08-11 23:21 UTC, IamShobe commented on src/porfavor/server/api.py
> +        return "No file was supplied in the request", 400
here and everywhere else

2018-08-11 23:21 UTC, IamShobe commented on src/porfavor/server/main.py
> +        os.path.dirname(os.path.abspath(__file__)),
that can   fit in 1 line no??

2018-10-01 17:46 UTC, osherdp commented on src/porfavor/client.py
> +        str: bytes of the zip file containing required files.
Actually, the convention should be with a colon:
[https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)
(Search for "Returns:")

2018-10-03 12:00 UTC, merged